# Generated by Django 3.2.15 on 2023-09-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Новый'), (2, 'Принят'), (3, 'Передан курьеру'), (4, 'Выполнен')], default=1, verbose_name='статус'),
        ),
    ]
