# Generated by Django 3.2.15 on 2023-10-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_order_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='restaurants',
            field=models.ManyToManyField(related_name='products', to='foodcartapp.Restaurant', verbose_name='рестораны'),
        ),
    ]
